/**
 * The guest SDK, as the one string of JavaScript every script sandbox runs
 * first (packages/script/src/guest, docs/PLAN-SCRIPTS.md §6.1): bundled by
 * Bun, unminified so what a script's fault names stays readable, and kept as
 * packages/script/src/generated/guest.ts.
 *
 *   npm run gen:script-guest               write it
 *   npm run gen:script-guest -- --check    fail if it is out of date (CI)
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const ENTRY = resolve(ROOT, 'packages', 'script', 'src', 'guest', 'sdk.ts');
const FILE = resolve(ROOT, 'packages', 'script', 'src', 'generated', 'guest.ts');

const built = await Bun.build({ entrypoints: [ENTRY], target: 'browser', format: 'iife', minify: false });
if (!built.success) {
  for (const log of built.logs) console.error(log);
  process.exit(1);
}
const code = (await built.outputs[0]!.text()).replace(/\r\n/g, '\n').trim();

const written = [
  '/*',
  '  Generated by scripts/gen-script-guest.ts from src/guest/sdk.ts: do not',
  '  edit. The guest SDK, run first in every sandbox (docs/PLAN-SCRIPTS.md §6.1).',
  '*/',
  '',
  `export const GUEST_SDK: string = ${JSON.stringify(code)};`,
  '',
].join('\n');
const kept = existsSync(FILE) ? readFileSync(FILE, 'utf8').replace(/\r\n/g, '\n') : null;

if (process.argv.includes('--check')) {
  if (kept !== written) {
    console.error('packages/script/src/generated/guest.ts is not the guest SDK as written: run `npm run gen:script-guest`.');
    process.exit(1);
  }
  console.log('The scripts’ guest SDK is current.');
} else if (kept !== written) {
  writeFileSync(FILE, written);
  console.log('Wrote packages/script/src/generated/guest.ts.');
} else console.log('packages/script/src/generated/guest.ts is current.');
