/**
 * Writes the app's registry of installed packages: client/src/generated/.
 * See docs/ARCHITECTURE.md §3.
 *
 * The server finds device types, protocols and transports at runtime. The app
 * cannot: Metro bundles what is imported, and an app store build must not
 * download code. So this finds every installed package and writes the files
 * importing them, each for where it runs (docs/PLAN-SHARED-CORE.md, phase 6):
 *
 *   installed.ts       what a hub installs: device types and what they bring
 *                      to automations, protocols, transport definitions — no
 *                      React, so a browser's worker builds a hub from it
 *   transports.ts      each transport's entry for a phone
 *   transports.web.ts  each transport's entry for a browser's page
 *   registry.ts        the screens and pictures device types ship
 *
 * The app runs the same code the server does, and these are the only files
 * in it that import a device, protocol or transport.
 *
 *   npm run gen:devices              write them
 *   npm run gen:devices -- --check   fail if one is out of date (CI)
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const ROOT = resolve(import.meta.dirname, '..');
const GENERATED = resolve(ROOT, 'client/src/generated');

type Manifest = {
  name: string;
  exports?: Record<string, string>;
  kraftverk?: {
    deviceType?: string;
    /** What the package brings to automations: its recipes and functions. */
    automation?: string;
    ui?: string;
    /** Pictures of the device as it looks, in order: the first is shown unless its owner picks another. */
    assets?: { images?: string[] };
    protocol?: string;
    transport?: { definition?: string; system?: string; web?: string; native?: string };
  };
};

/** The import specifier a package exports a file under, or a clear failure. */
function exported(manifest: Manifest, file: string): string {
  const key = Object.entries(manifest.exports ?? {}).find(([, target]) => target === file)?.[0];
  if (!key) throw new Error(`${manifest.name} must export ${file} in its package.json "exports"`);
  return key === '.' ? manifest.name : `${manifest.name}${key.slice(1)}`;
}

const local = (name: string, suffix = '') =>
  name.replace(/^@kraftverk\//, '').replace(/[^a-zA-Z0-9]+(.)/g, (_, c: string) => c.toUpperCase()) + suffix;

function packages(parent: string): { dir: string; manifest: Manifest }[] {
  const root = resolve(ROOT, parent);
  let entries: string[];
  try {
    entries = readdirSync(root);
  } catch {
    return [];
  }
  return entries.sort().flatMap((entry) => {
    try {
      const dir = resolve(root, entry);
      return [{ dir, manifest: JSON.parse(readFileSync(resolve(dir, 'package.json'), 'utf8')) as Manifest }];
    } catch {
      return [];
    }
  });
}

/**
 * What a device image must be to go in the app: a PNG, on a transparent
 * background so it sits on a card in either theme, and small enough that a
 * list of devices does not download megabytes. It is never drawn larger than a
 * few hundred points, so 1024 pixels is room for a sharp screen with margin.
 */
const IMAGE_MAX_PX = 1024;
const IMAGE_MAX_BYTES = 512 * 1024;

function checkImage(manifest: Manifest, dir: string, file: string): void {
  const where = `${manifest.name}: ${file}`;
  let bytes: Buffer;
  try {
    bytes = readFileSync(resolve(dir, file));
  } catch {
    throw new Error(`${where} does not exist`);
  }
  const png = bytes.length > 26 && bytes.toString('latin1', 1, 4) === 'PNG';
  if (!png) throw new Error(`${where} must be a PNG`);
  const width = bytes.readUInt32BE(16);
  const height = bytes.readUInt32BE(20);
  const colourType = bytes[25];
  // Colour types 4 and 6 carry alpha; a palette image may carry it in a tRNS chunk.
  const transparent = colourType === 4 || colourType === 6 || bytes.includes('tRNS');
  if (!transparent) throw new Error(`${where} must have a transparent background, so it sits on a card in light and dark alike`);
  if (width > IMAGE_MAX_PX || height > IMAGE_MAX_PX) throw new Error(`${where} is ${width}×${height}; at most ${IMAGE_MAX_PX}×${IMAGE_MAX_PX} — it is never drawn larger than a few hundred points`);
  if (bytes.length > IMAGE_MAX_BYTES) throw new Error(`${where} is ${Math.round(bytes.length / 1024)} KB; at most ${IMAGE_MAX_BYTES / 1024} KB, or every list of devices downloads it`);
}

/** One file being written: its imports, and what follows them. */
type Written = { file: string; what: string; imports: string[]; body: string[] };

const HEADER = (what: string) => [
  '/*',
  '  Generated by `npm run gen:devices` from the installed packages. Do not edit:',
  '  add a package, and run it again. See scripts/gen-devices.ts.',
  '',
  `  ${what}`,
  '*/',
  '',
];

const installed: Written = { file: 'installed.ts', what: 'What a hub installs, with no screens: the app keeps its own home from this.', imports: [], body: [] };
const screens: Written = { file: 'registry.ts', what: 'The screens and pictures device types ship.', imports: [], body: [] };
const onPhone: Written = { file: 'transports.ts', what: 'Each transport as a phone runs it.', imports: [], body: [] };
const onPage: Written = { file: 'transports.web.ts', what: "Each transport as a browser's page runs it.", imports: [], body: [] };

const types: string[] = [];
const uis: string[] = [];
const pictures: string[] = [];
const protocols: string[] = [];
const definitions: string[] = [];
const entries = { native: [] as string[], web: [] as string[] };

for (const { dir, manifest } of [...packages('packages/devices'), ...packages('packages/services')]) {
  const { deviceType, ui, assets, automation } = manifest.kraftverk ?? {};
  if (!deviceType) continue;
  const type = ((await import(pathToFileURL(resolve(dir, deviceType)).href)) as { default?: { id?: string } }).default;
  if (!type?.id) throw new Error(`${manifest.name}: its deviceType entry has no default export with an id`);
  installed.imports.push(`import ${local(manifest.name, 'Type')} from '${exported(manifest, deviceType)}';`);
  if (automation) installed.imports.push(`import ${local(manifest.name, 'Automation')} from '${exported(manifest, automation)}';`);
  types.push(`  { type: ${local(manifest.name, 'Type')}, automation: ${automation ? local(manifest.name, 'Automation') : 'null'} },`);
  if (ui) {
    screens.imports.push(`import ${local(manifest.name, 'Ui')} from '${exported(manifest, ui)}';`);
    uis.push(`  '${type.id}': ${local(manifest.name, 'Ui')},`);
  }
  if (assets?.images?.length) {
    for (const image of assets.images) checkImage(manifest, dir, image);
    // require, not import: Metro makes each file an asset of the build, on the web and on a phone alike.
    const required = assets.images.map((image) => `require('${exported(manifest, image)}')`).join(', ');
    pictures.push(`  '${type.id}': { images: [${required}] },`);
  }
}

for (const { manifest } of packages('packages/protocols')) {
  const entry = manifest.kraftverk?.protocol;
  if (!entry) continue;
  installed.imports.push(`import ${local(manifest.name)} from '${exported(manifest, entry)}';`);
  protocols.push(`  ${local(manifest.name)},`);
}

for (const { dir, manifest } of packages('packages/transports')) {
  const entry = manifest.kraftverk?.transport;
  if (!entry?.definition) continue;
  installed.imports.push(`import ${local(manifest.name)} from '${exported(manifest, entry.definition)}';`);
  definitions.push(`  ${local(manifest.name)},`);
  for (const [platform, written] of [['native', onPhone], ['web', onPage]] as const) {
    const file = entry[platform];
    if (!file) continue;
    // Its definition's id, read where it is declared: the key the hub asks by.
    const definition = ((await import(pathToFileURL(resolve(dir, entry.definition)).href)) as { default?: { id?: string } }).default;
    if (!definition?.id) throw new Error(`${manifest.name}: its transport definition has no default export with an id`);
    written.imports.push(`import ${local(manifest.name)} from '${exported(manifest, file)}';`);
    entries[platform].push(`  '${definition.id}': ${local(manifest.name)},`);
  }
}

installed.body = [
  "import type { AutomationContribution } from '@kraftverk/automation';",
  "import type { DeviceType, Protocol, TransportDefinition } from '@kraftverk/device-sdk';",
  '',
  ...installed.imports,
  '',
  '/** Every installed device type, and what its package brings to automations beside it: the same code the server runs. */',
  'export const DEVICE_TYPES: readonly { type: DeviceType<any>; automation: AutomationContribution | null }[] = [',
  ...types,
  '];',
  '',
  'export const PROTOCOLS: readonly Protocol[] = [',
  ...protocols,
  '];',
  '',
  "/** Every transport, as data: what the hub knows of it wherever it runs. Its entry for a place is that place's file. */",
  'export const TRANSPORTS: readonly TransportDefinition[] = [',
  ...definitions,
  '];',
  '',
];

screens.body = [
  "import type { DeviceAssets, DeviceUi } from '../features/devices/registry';",
  '',
  ...screens.imports,
  '',
  '/** Screens a device type ships, by device type id. */',
  'export const DEVICE_UI: Readonly<Record<string, DeviceUi>> = {',
  ...uis,
  '};',
  '',
  '/** Pictures a device type ships, by device type id. */',
  'export const DEVICE_ASSETS: Readonly<Record<string, DeviceAssets>> = {',
  ...pictures,
  '};',
  '',
];

for (const [platform, written] of [['native', onPhone], ['web', onPage]] as const) {
  written.body = [
    "import type { TransportFactory } from '@kraftverk/device-sdk';",
    '',
    ...written.imports,
    '',
    `/** Each transport that runs ${platform === 'web' ? "on a browser's page" : 'on a phone'}, by its id: one without an entry here cannot. */`,
    'export const TRANSPORT_ENTRIES: Readonly<Record<string, TransportFactory>> = {',
    ...entries[platform],
    '};',
    '',
  ];
}

const files = [installed, screens, onPhone, onPage].map((written) => ({ path: resolve(GENERATED, written.file), source: [...HEADER(written.what), ...written.body].join('\n'), file: written.file }));
const summary = `${types.length} device type(s), ${uis.length} with screens, ${pictures.length} with a picture, ${protocols.length} protocol(s), ${definitions.length} transport(s)`;

if (process.argv.includes('--check')) {
  const stale = files.filter(({ path, source }) => {
    try {
      return readFileSync(path, 'utf8').replaceAll('\r\n', '\n') !== source;
    } catch {
      return true; // missing counts as stale
    }
  });
  if (stale.length) {
    console.error(`${stale.map(({ file }) => `client/src/generated/${file}`).join(', ')} out of date. Run: npm run gen:devices`);
    process.exit(1);
  }
  console.log(`The app's registry is current: ${summary}.`);
} else {
  for (const { path, source } of files) writeFileSync(path, source);
  console.log(`Wrote the app's registry: ${summary}.`);
}
